# Generated by Django 4.2.9 on 2024-03-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='telephone',
            field=models.CharField(max_length=500),
        ),
    ]
