# Generated by Django 4.2.9 on 2024-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_alter_contactinfo_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
