# Generated by Django 4.2.9 on 2024-06-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_quote_quote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
