# Generated by Django 4.2.9 on 2024-06-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_quote_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
